DROP TABLE IF EXISTS TB_HEROIS 
CREATE TABLE TB_HEROIS(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

-- insert na tabela
INSERT INTO TB_HEROIS NOME,PODER 
VALUES 
('FLASH','VELOCIDADE'),
('AQUAMAN','TELEPATIA AQUATICA'),
('BATMAN','DINHEIRO')

-- select na tabela

SELECT * FROM TB_HEROIS


-- SELECT COM WHERE 

SELECT * FROM TB_HEOIS WHERE NOME = 'FLASH';

-- UPDATE 
UPDATE TB_HEROIS SET NOME ='GOKU' WHERE ID = 1;

--DELETE
DELETE FROM TB_HEROIS WHERE ID=2;